variables:
  tf_state_rg: "tfstate-rg" # name of the resource group to create/use for the terraform state file
  tz_state_location: "west us" # location of the resource group to create/use for the terraform state file
  tf_state_sa_name: "tfstatesmartfan" # name of of the storage account to create/use for the terraform state file
  tf_state_container_name: "tfstate" # name of of the container to create/use for the terraform state file
 
pool:
  vmImage: ubuntu-latest
 
steps:

  - task: AzureCLI@2
    displayName: "Create/Check the Terraform Statefile Azure Storage Account"
    inputs:
      azureSubscription: 'Mahwish VS Enterprise Subscription – MPN (e09e8db9-bd86-48ae-8eeb-eda17abcc24a)'
      addSpnToEnvironment: true
      scriptType: "bash"
      scriptLocation: "inlineScript"
      inlineScript: |
    
        az group create --name $(tf_state_rg) --location $(tz_state_location)
        az storage account create --resource-group $(tf_state_rg) --name $(tf_state_sa_name) --sku Standard_GRS --encryption-services blob
        ACCOUNT_KEY=$(az storage account keys list --resource-group $(tf_state_rg) --account-name $(tf_state_sa_name) --query [0].value -o tsv)
        az storage container create --name $(tf_state_container_name) --account-name $(tf_state_sa_name) --account-key $ACCOUNT_KEY
        echo "##vso[task.setvariable variable=tf_state_sa_key]$ACCOUNT_KEY"
  
  - task: TerraformTaskV1@0
    displayName: "Run > terraform init"
    inputs:
      command: "init"
      backendServiceArm: 'Mahwish VS Enterprise Subscription – MPN (e09e8db9-bd86-48ae-8eeb-eda17abcc24a)'
      #workingDirectory: '$(System.DefaultWorkingDirectory)'
      backendAzureRmResourceGroupName: "$(tf_state_rg)"
      backendAzureRmStorageAccountName: "$(tf_state_sa_name)"
      backendAzureRmContainerName: $(tf_state_container_name)
      backendAzureRmKey: "terraform.tstate"
  
 
  - task: TerraformTaskV1@0
    displayName: "Run > terraform plan"
    inputs:
      command: "plan"
      environmentServiceNameAzureRM: 'Mahwish VS Enterprise Subscription – MPN (e09e8db9-bd86-48ae-8eeb-eda17abcc24a)'
 
  - task: TerraformTaskV1@0
    displayName: "Run > terraform apply"
    inputs:
      command: "apply"
      environmentServiceNameAzureRM: 'Mahwish VS Enterprise Subscription – MPN (e09e8db9-bd86-48ae-8eeb-eda17abcc24a)'